// <auto-generated />
using System;
using CCPS_Project_New_Tech.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CCPS_Project_New_Tech.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211211211917_FixSessionsTable")]
    partial class FixSessionsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CCPS_Project_New_Tech.Models.Personne", b =>
                {
                    b.Property<int>("PersonneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonneID"), 1L, 1);

                    b.Property<string>("DDN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreer")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonneID");

                    b.ToTable("Personnes");
                });

            modelBuilder.Entity("CCPS_Project_New_Tech.Models.Sessions", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionID"), 1L, 1);

                    b.Property<int>("Actif")
                        .HasColumnType("int");

                    b.Property<string>("Byusername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClasseID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCommence")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Heures")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JourRencontre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxEtudiants")
                        .HasColumnType("int");

                    b.Property<int>("MontantParticipation")
                        .HasColumnType("int");

                    b.Property<string>("Remarque")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionID");

                    b.ToTable("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
